### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by iambeingtracked** [syuilo/Misskey#11358]
## 💡 Summary

I can't run Misskey with "NODE_ENV=production pnpm run start"

> misskey@13.14.1 start /home/misskey/misskey
> pnpm check:connect && cd packages/backend && node ./built/boot/index.js

> misskey@13.14.1 check:connect /home/misskey/misskey
> cd packages/backend && pnpm check:connect

> backend@ check:connect /home/misskey/misskey/packages/backend
> node ./check_connect.js

(node:1626) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1626) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module 'slacc-linux-x64-musl'
Require stack:
- /home/misskey/misskey/node_modules/.pnpm/slacc@0.0.9/node_modules/slacc/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/home/misskey/misskey/node_modules/.pnpm/slacc@0.0.9/node_modules/slacc/index.js:177:31)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/misskey/misskey/node_modules/.pnpm/slacc@0.0.9/node_modules/slacc/index.js'
  ]
}

Node.js v20.5.0
 ELIFECYCLE  Command failed with exit code 1.
 
Github's markdown formatting is still broken
## 🥰 Expected Behavior
It should run

## 🤬 Actual Behavior
It doesn't

## 📝 Steps to Reproduce

1.  Follow the installation guide: https://misskey-hub.net/en/docs/install/manual.html

## 📌 Environment

Alpine Linux 3.18 in an LXC container

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: 
* Node: 20.5.0
* PostgreSQL: 15.3
* Redis: 7.0.12
* OS and Architecture: Alpine Linux 3.18 in an LXC container x86-64

**Comment by CyberRex0** [comment]
slacc supports Alpine Linux musl, but prebuilt binary for x64 is not provided (but ARM does)

**Comment by iambeingtracked** [comment]
So how do I get it? I don't know what slacc is, is it this python thingy? https://pypi.org/project/slacc/

**Comment by iambeingtracked** [comment]
Oh okay I searched the repo and found what it is, here's what `npm search slac` gives:
````
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
slacc                     | An internal library… | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-linux-x64-gnu       | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-linux-arm64-gnu     | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-darwin-universal    | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-linux-arm64-musl    | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-darwin-arm64        | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-darwin-x64          | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-linux-arm-gnueabihf | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-android-arm64       | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-win32-x64-msvc      | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-android-arm-eabi    | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-freebsd-x64         | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
slacc-win32-arm64-msvc    | This is the…         | =acid-chicken   | 2023-05-12 | 0.0.9    |
````

Seems like slacc-linux-x64-musl isn't there, but how do I run it then?

**Comment by acid-chicken** [comment]
I published `slacc@0.0.10`. So, now you can use `slacc-linux-x64-musl` by updating `slacc`.

**Comment by iambeingtracked** [comment]
I tried installing it all again but it still doesn't work with the same error, here's what npm list says:
````
npm ERR! code ELSPROBLEMS
npm ERR! extraneous: @eslint-community/eslint-utils@4.4.0 /home/misskey/misskey/node_modules/@eslint-community/eslint-utils
npm ERR! extraneous: @eslint-community/regexpp@4.5.0 /home/misskey/misskey/node_modules/@eslint-community/regexpp
npm ERR! extraneous: @eslint/eslintrc@2.1.0 /home/misskey/misskey/node_modules/@eslint/eslintrc
npm ERR! extraneous: @eslint/js@8.44.0 /home/misskey/misskey/node_modules/@eslint/js
npm ERR! extraneous: @typescript-eslint/scope-manager@5.61.0 /home/misskey/misskey/node_modules/@typescript-eslint/scope-manager
npm ERR! extraneous: @typescript-eslint/type-utils@5.61.0 /home/misskey/misskey/node_modules/@typescript-eslint/type-utils
npm ERR! extraneous: @typescript-eslint/types@5.61.0 /home/misskey/misskey/node_modules/@typescript-eslint/types
npm ERR! extraneous: @typescript-eslint/visitor-keys@5.61.0 /home/misskey/misskey/node_modules/@typescript-eslint/visitor-keys
npm ERR! missing: backend@file:/home/misskey/misskey/packages/backend, required by misskey@13.14.1
npm ERR! extraneous: eslint-formatter-pretty@4.1.0 /home/misskey/misskey/node_modules/eslint-formatter-pretty
npm ERR! extraneous: eslint-import-resolver-node@0.3.7 /home/misskey/misskey/node_modules/eslint-import-resolver-node
npm ERR! extraneous: eslint-module-utils@2.7.4 /home/misskey/misskey/node_modules/eslint-module-utils
npm ERR! extraneous: eslint-rule-docs@1.1.235 /home/misskey/misskey/node_modules/eslint-rule-docs
npm ERR! extraneous: eslint-scope@7.2.0 /home/misskey/misskey/node_modules/eslint-scope
npm ERR! missing: frontend@file:/home/misskey/misskey/packages/frontend, required by misskey@13.14.1
npm ERR! missing: sw@file:/home/misskey/misskey/packages/sw, required by misskey@13.14.1
npm ERR! extraneous: vue-eslint-parser@9.3.1 /home/misskey/misskey/node_modules/vue-eslint-parser
misskey@13.14.1 /home/misskey/misskey
├── @eslint-community/eslint-utils@4.4.0 extraneous -> ./node_modules/.pnpm/@eslint-community+eslint-utils@4.4.0_eslint@8.45.0/node_modules/@eslint-community/eslint-utils
├── @eslint-community/regexpp@4.5.0 extraneous -> ./node_modules/.pnpm/@eslint-community+regexpp@4.5.0/node_modules/@eslint-community/regexpp
├── @eslint/eslintrc@2.1.0 extraneous -> ./node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc
├── @eslint/js@8.44.0 extraneous -> ./node_modules/.pnpm/@eslint+js@8.44.0/node_modules/@eslint/js
├── @tensorflow/tfjs-core@4.4.0 -> ./node_modules/.pnpm/@tensorflow+tfjs-core@4.4.0/node_modules/@tensorflow/tfjs-core
├── @types/gulp-rename@2.0.1 -> ./node_modules/.pnpm/@types+gulp-rename@2.0.1/node_modules/@types/gulp-rename
├── @types/gulp@4.0.10 -> ./node_modules/.pnpm/@types+gulp@4.0.10/node_modules/@types/gulp
├── @typescript-eslint/eslint-plugin@5.61.0 -> ./node_modules/.pnpm/@typescript-eslint+eslint-plugin@5.61.0_@typescript-eslint+parser@5.61.0_eslint@8.45.0_typescript@5.1.6/node_modules/@typescript-eslint/eslint-plugin
├── @typescript-eslint/parser@5.61.0 -> ./node_modules/.pnpm/@typescript-eslint+parser@5.61.0_eslint@8.45.0_typescript@5.1.6/node_modules/@typescript-eslint/parser
├── @typescript-eslint/scope-manager@5.61.0 extraneous -> ./node_modules/.pnpm/@typescript-eslint+scope-manager@5.61.0/node_modules/@typescript-eslint/scope-manager
├── @typescript-eslint/type-utils@5.61.0 extraneous -> ./node_modules/.pnpm/@typescript-eslint+type-utils@5.61.0_eslint@8.45.0_typescript@5.1.6/node_modules/@typescript-eslint/type-utils
├── @typescript-eslint/types@5.61.0 extraneous -> ./node_modules/.pnpm/@typescript-eslint+types@5.61.0/node_modules/@typescript-eslint/types
├── @typescript-eslint/visitor-keys@5.61.0 extraneous -> ./node_modules/.pnpm/@typescript-eslint+visitor-keys@5.61.0/node_modules/@typescript-eslint/visitor-keys
├── UNMET DEPENDENCY backend@file:/home/misskey/misskey/packages/backend
├── cross-env@7.0.3 -> ./node_modules/.pnpm/cross-env@7.0.3/node_modules/cross-env
├── cypress@12.17.1 -> ./node_modules/.pnpm/cypress@12.17.1/node_modules/cypress
├── eslint-formatter-pretty@4.1.0 extraneous -> ./node_modules/.pnpm/eslint-formatter-pretty@4.1.0/node_modules/eslint-formatter-pretty
├── eslint-import-resolver-node@0.3.7 extraneous -> ./node_modules/.pnpm/eslint-import-resolver-node@0.3.7/node_modules/eslint-import-resolver-node
├── eslint-module-utils@2.7.4 extraneous -> ./node_modules/.pnpm/eslint-module-utils@2.7.4_@typescript-eslint+parser@5.61.0_eslint-import-resolver-node@0.3.7_eslint@8.45.0/node_modules/eslint-module-utils
├── eslint-rule-docs@1.1.235 extraneous -> ./node_modules/.pnpm/eslint-rule-docs@1.1.235/node_modules/eslint-rule-docs
├── eslint-scope@7.2.0 extraneous -> ./node_modules/.pnpm/eslint-scope@7.2.0/node_modules/eslint-scope
├── eslint@8.45.0 -> ./node_modules/.pnpm/eslint@8.45.0/node_modules/eslint
├── execa@7.1.1 -> ./node_modules/.pnpm/execa@7.1.1/node_modules/execa
├── UNMET DEPENDENCY frontend@file:/home/misskey/misskey/packages/frontend
├── gulp-cssnano@2.1.3 -> ./node_modules/.pnpm/gulp-cssnano@2.1.3/node_modules/gulp-cssnano
├── gulp-rename@2.0.0 -> ./node_modules/.pnpm/gulp-rename@2.0.0/node_modules/gulp-rename
├── gulp-replace@1.1.4 -> ./node_modules/.pnpm/gulp-replace@1.1.4/node_modules/gulp-replace
├── gulp-terser@2.1.0 -> ./node_modules/.pnpm/gulp-terser@2.1.0/node_modules/gulp-terser
├── gulp@4.0.2 -> ./node_modules/.pnpm/gulp@4.0.2/node_modules/gulp
├── js-yaml@4.1.0 -> ./node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml
├── start-server-and-test@2.0.0 -> ./node_modules/.pnpm/start-server-and-test@2.0.0/node_modules/start-server-and-test
├── UNMET DEPENDENCY sw@file:/home/misskey/misskey/packages/sw
├── typescript@5.1.6 -> ./node_modules/.pnpm/typescript@5.1.6/node_modules/typescript
└── vue-eslint-parser@9.3.1 extraneous -> ./node_modules/.pnpm/vue-eslint-parser@9.3.1_eslint@8.45.0/node_modules/vue-eslint-parser


npm ERR! A complete log of this run can be found in: /home/misskey/.npm/_logs/2023-07-23T13_40_48_569Z-debug-0.log
````

And I don't see any mentions of slacc there, I tried globally installing it from the root user but it still doesn't work

**Comment by iambeingtracked** [comment]
Here's the log from an another run of npm list:
````
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.6
2 info using node@v20.5.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/misskey/misskey/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/misskey/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 7ms
17 timing npm:load:configload Completed in 7ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm update
21 verbose argv "update"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 4ms
25 verbose logfile logs-max:10 dir:/home/misskey/.npm/_logs/2023-07-23T14_15_11_949Z-
26 verbose logfile /home/misskey/.npm/_logs/2023-07-23T14_15_11_949Z-debug-0.log
27 timing npm:load:logFile Completed in 7ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 21ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile done cleaning log files
33 timing idealTree:init Completed in 84ms
34 timing idealTree:userRequests Completed in 0ms
35 silly idealTree buildDeps
36 silly fetch manifest execa@7.1.1
37 http fetch GET 200 https://registry.npmjs.org/execa 523ms (cache miss)
38 silly fetch manifest gulp@4.0.2
39 http fetch GET 200 https://registry.npmjs.org/gulp 50ms (cache miss)
40 silly fetch manifest gulp-cssnano@2.1.3
41 http fetch GET 200 https://registry.npmjs.org/gulp-cssnano 855ms (cache miss)
42 silly fetch manifest gulp-rename@2.0.0
43 http fetch GET 200 https://registry.npmjs.org/gulp-rename 54ms (cache miss)
44 silly fetch manifest gulp-replace@1.1.4
45 http fetch GET 200 https://registry.npmjs.org/gulp-replace 801ms (cache miss)
46 silly fetch manifest gulp-terser@2.1.0
47 http fetch GET 200 https://registry.npmjs.org/gulp-terser 801ms (cache miss)
48 silly fetch manifest js-yaml@4.1.0
49 http fetch GET 200 https://registry.npmjs.org/js-yaml 68ms (cache miss)
50 silly fetch manifest typescript@5.1.6
51 http fetch GET 200 https://registry.npmjs.org/typescript 670ms (cache miss)
52 silly fetch manifest @tensorflow/tfjs-core@4.4.0
53 http fetch GET 200 https://registry.npmjs.org/@tensorflow%2ftfjs-core 388ms (cache miss)
54 silly fetch manifest @types/gulp@4.0.10
55 http fetch GET 200 https://registry.npmjs.org/@types%2fgulp 57ms (cache miss)
56 silly fetch manifest @types/gulp-rename@2.0.1
57 http fetch GET 200 https://registry.npmjs.org/@types%2fgulp-rename 76ms (cache miss)
58 silly fetch manifest @typescript-eslint/eslint-plugin@5.61.0
59 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2feslint-plugin 746ms (cache miss)
60 silly fetch manifest @typescript-eslint/parser@5.61.0
61 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fparser 639ms (cache miss)
62 silly fetch manifest eslint@8.45.0
63 http fetch GET 200 https://registry.npmjs.org/eslint 128ms (cache miss)
64 silly fetch manifest cross-env@7.0.3
65 http fetch GET 200 https://registry.npmjs.org/cross-env 59ms (cache miss)
66 silly fetch manifest cypress@12.17.1
67 http fetch GET 200 https://registry.npmjs.org/cypress 122ms (cache miss)
68 silly fetch manifest start-server-and-test@2.0.0
69 http fetch GET 200 https://registry.npmjs.org/start-server-and-test 62ms (cache miss)
70 silly placeDep ROOT @tensorflow/tfjs-core@4.4.0 OK for: misskey@13.14.1 want: 4.4.0
71 silly fetch manifest @types/long@^4.0.1
72 silly fetch manifest @types/offscreencanvas@~2019.7.0
73 silly fetch manifest @types/seedrandom@^2.4.28
74 silly fetch manifest @types/webgl-ext@0.0.30
75 silly fetch manifest @webgpu/types@0.1.30
76 silly fetch manifest long@4.0.0
77 silly fetch manifest node-fetch@~2.6.1
78 silly fetch manifest seedrandom@^3.0.5
79 silly placeDep ROOT @types/gulp@4.0.10 OK for: misskey@13.14.1 want: 4.0.10
80 silly fetch manifest @types/undertaker@>=1.2.6
81 silly fetch manifest @types/vinyl-fs@*
82 silly fetch manifest chokidar@^3.3.1
83 silly placeDep ROOT @types/gulp-rename@2.0.1 OK for: misskey@13.14.1 want: 2.0.1
84 silly fetch manifest @types/node@*
85 silly fetch manifest @types/vinyl@*
86 silly placeDep ROOT @typescript-eslint/eslint-plugin@5.61.0 OK for: misskey@13.14.1 want: 5.61.0
87 silly placeDep ROOT @typescript-eslint/parser@5.61.0 OK for: @typescript-eslint/eslint-plugin@5.61.0 want: ^5.0.0
88 silly placeDep ROOT eslint@8.45.0 OK for: @typescript-eslint/parser@5.61.0 want: ^6.0.0 || ^7.0.0 || ^8.0.0
89 silly fetch manifest @eslint-community/regexpp@^4.4.0
90 silly fetch manifest @typescript-eslint/scope-manager@5.61.0
91 silly fetch manifest @typescript-eslint/type-utils@5.61.0
92 silly fetch manifest @typescript-eslint/utils@5.61.0
93 silly fetch manifest debug@^4.3.4
94 silly fetch manifest graphemer@^1.4.0
95 silly fetch manifest ignore@^5.2.0
96 silly fetch manifest natural-compare-lite@^1.4.0
97 silly fetch manifest semver@^7.3.7
98 silly fetch manifest tsutils@^3.21.0
99 silly fetch manifest @typescript-eslint/types@5.61.0
100 silly fetch manifest @typescript-eslint/typescript-estree@5.61.0
101 silly fetch manifest @eslint-community/eslint-utils@^4.2.0
102 silly fetch manifest @eslint/eslintrc@^2.1.0
103 silly fetch manifest @eslint/js@8.44.0
104 silly fetch manifest @humanwhocodes/config-array@^0.11.10
105 silly fetch manifest @humanwhocodes/module-importer@^1.0.1
106 silly fetch manifest @nodelib/fs.walk@^1.2.8
107 silly fetch manifest ajv@^6.10.0
108 silly fetch manifest chalk@^4.0.0
109 silly fetch manifest cross-spawn@^7.0.2
110 silly fetch manifest debug@^4.3.2
111 silly fetch manifest doctrine@^3.0.0
112 silly fetch manifest escape-string-regexp@^4.0.0
113 silly fetch manifest eslint-scope@^7.2.0
114 silly fetch manifest eslint-visitor-keys@^3.4.1
115 silly fetch manifest espree@^9.6.0
116 silly fetch manifest esquery@^1.4.2
117 silly fetch manifest esutils@^2.0.2
118 silly fetch manifest fast-deep-equal@^3.1.3
119 silly fetch manifest file-entry-cache@^6.0.1
120 silly fetch manifest find-up@^5.0.0
121 silly fetch manifest glob-parent@^6.0.2
122 silly fetch manifest globals@^13.19.0
123 silly fetch manifest imurmurhash@^0.1.4
124 silly fetch manifest is-glob@^4.0.0
125 silly fetch manifest is-path-inside@^3.0.3
126 silly fetch manifest js-yaml@^4.1.0
127 silly fetch manifest json-stable-stringify-without-jsonify@^1.0.1
128 silly fetch manifest levn@^0.4.1
129 silly fetch manifest lodash.merge@^4.6.2
130 silly fetch manifest minimatch@^3.1.2
131 silly fetch manifest natural-compare@^1.4.0
132 silly fetch manifest optionator@^0.9.3
133 silly fetch manifest strip-ansi@^6.0.1
134 silly fetch manifest text-table@^0.2.0
135 silly placeDep ROOT backend@ OK for: misskey@13.14.1 want: file:/home/misskey/misskey/packages/backend
136 silly placeDep ROOT cross-env@7.0.3 OK for: misskey@13.14.1 want: 7.0.3
137 silly fetch manifest cross-spawn@^7.0.1
138 silly placeDep ROOT cypress@12.17.1 OK for: misskey@13.14.1 want: 12.17.1
139 silly fetch manifest @cypress/request@^2.88.11
140 silly fetch manifest @cypress/xvfb@^1.2.4
141 silly fetch manifest @types/node@^14.14.31
142 silly fetch manifest @types/sinonjs__fake-timers@8.1.1
143 silly fetch manifest @types/sizzle@^2.3.2
144 silly fetch manifest arch@^2.2.0
145 silly fetch manifest blob-util@^2.0.2
146 silly fetch manifest bluebird@^3.7.2
147 silly fetch manifest buffer@^5.6.0
148 silly fetch manifest cachedir@^2.3.0
149 silly fetch manifest chalk@^4.1.0
150 silly fetch manifest check-more-types@^2.24.0
151 silly fetch manifest cli-cursor@^3.1.0
152 silly fetch manifest cli-table3@~0.6.1
153 silly fetch manifest commander@^6.2.1
154 silly fetch manifest common-tags@^1.8.0
155 silly fetch manifest dayjs@^1.10.4
156 silly fetch manifest enquirer@^2.3.6
157 silly fetch manifest eventemitter2@6.4.7
158 silly fetch manifest execa@4.1.0
159 silly fetch manifest executable@^4.1.1
160 silly fetch manifest extract-zip@2.0.1
161 silly fetch manifest figures@^3.2.0
162 silly fetch manifest fs-extra@^9.1.0
163 silly fetch manifest getos@^3.2.1
164 silly fetch manifest is-ci@^3.0.0
165 silly fetch manifest is-installed-globally@~0.4.0
166 silly fetch manifest lazy-ass@^1.6.0
167 silly fetch manifest listr2@^3.8.3
168 silly fetch manifest lodash@^4.17.21
169 silly fetch manifest log-symbols@^4.0.0
170 silly fetch manifest minimist@^1.2.8
171 silly fetch manifest ospath@^1.2.2
172 silly fetch manifest pretty-bytes@^5.6.0
173 silly fetch manifest proxy-from-env@1.0.0
174 silly fetch manifest request-progress@^3.0.0
175 silly fetch manifest semver@^7.5.3
176 silly fetch manifest supports-color@^8.1.1
177 silly fetch manifest tmp@~0.2.1
178 silly fetch manifest untildify@^4.0.0
179 silly fetch manifest yauzl@^2.10.0
180 silly placeDep ROOT execa@7.1.1 OK for: misskey@13.14.1 want: 7.1.1
181 silly fetch manifest cross-spawn@^7.0.3
182 silly fetch manifest get-stream@^6.0.1
183 silly fetch manifest human-signals@^4.3.0
184 silly fetch manifest is-stream@^3.0.0
185 silly fetch manifest merge-stream@^2.0.0
186 silly fetch manifest npm-run-path@^5.1.0
187 silly fetch manifest onetime@^6.0.0
188 silly fetch manifest signal-exit@^3.0.7
189 silly fetch manifest strip-final-newline@^3.0.0
190 silly placeDep ROOT frontend@ OK for: misskey@13.14.1 want: file:/home/misskey/misskey/packages/frontend
191 silly placeDep ROOT gulp@4.0.2 OK for: misskey@13.14.1 want: 4.0.2
192 silly fetch manifest glob-watcher@^5.0.3
193 silly fetch manifest gulp-cli@^2.2.0
194 silly fetch manifest undertaker@^1.2.1
195 silly fetch manifest vinyl-fs@^3.0.0
196 silly placeDep ROOT gulp-cssnano@2.1.3 OK for: misskey@13.14.1 want: 2.1.3
197 silly fetch manifest buffer-from@^1.0.0
198 silly fetch manifest cssnano@^3.0.0
199 silly fetch manifest object-assign@^4.0.1
200 silly fetch manifest plugin-error@^1.0.1
201 silly fetch manifest vinyl-sourcemaps-apply@^0.2.1
202 silly placeDep ROOT gulp-rename@2.0.0 OK for: misskey@13.14.1 want: 2.0.0
203 silly placeDep ROOT gulp-replace@1.1.4 OK for: misskey@13.14.1 want: 1.1.4
204 silly fetch manifest @types/vinyl@^2.0.4
205 silly fetch manifest istextorbinary@^3.0.0
206 silly fetch manifest replacestream@^4.0.3
207 silly fetch manifest yargs-parser@>=5.0.0-security.0
208 silly placeDep ROOT gulp-terser@2.1.0 OK for: misskey@13.14.1 want: 2.1.0
209 silly fetch manifest terser@^5.9.0
210 silly fetch manifest through2@^4.0.2
211 silly placeDep ROOT js-yaml@4.1.0 OK for: misskey@13.14.1 want: 4.1.0
212 silly fetch manifest argparse@^2.0.1
213 silly placeDep ROOT start-server-and-test@2.0.0 OK for: misskey@13.14.1 want: 2.0.0
214 silly fetch manifest arg@^5.0.2
215 silly fetch manifest bluebird@3.7.2
216 silly fetch manifest check-more-types@2.24.0
217 silly fetch manifest debug@4.3.4
218 silly fetch manifest execa@5.1.1
219 silly fetch manifest lazy-ass@1.6.0
220 silly fetch manifest ps-tree@1.2.0
221 silly fetch manifest wait-on@7.0.1
222 silly placeDep ROOT sw@ OK for: misskey@13.14.1 want: file:/home/misskey/misskey/packages/sw
223 silly placeDep ROOT typescript@5.1.6 OK for: misskey@13.14.1 want: 5.1.6
224 http fetch GET 200 https://registry.npmjs.org/@types%2flong 244ms (cache miss)
225 http fetch GET 200 https://registry.npmjs.org/long 286ms (cache miss)
226 http fetch GET 200 https://registry.npmjs.org/@types%2fvinyl-fs 284ms (cache miss)
227 http fetch GET 200 https://registry.npmjs.org/chokidar 296ms (cache miss)
228 http fetch GET 200 https://registry.npmjs.org/@types%2fundertaker 305ms (cache miss)
229 http fetch GET 200 https://registry.npmjs.org/node-fetch 329ms (cache miss)
230 http fetch GET 200 https://registry.npmjs.org/ignore 402ms (cache miss)
231 http fetch GET 200 https://registry.npmjs.org/natural-compare-lite 448ms (cache miss)
232 http fetch GET 200 https://registry.npmjs.org/semver 541ms (cache miss)
233 http fetch GET 200 https://registry.npmjs.org/tsutils 595ms (cache miss)
234 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 702ms (cache miss)
235 http fetch GET 200 https://registry.npmjs.org/debug 751ms (cache miss)
236 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2futils 1027ms (cache miss)
237 http fetch GET 200 https://registry.npmjs.org/@eslint-community%2feslint-utils 1038ms (cache miss)
238 http fetch GET 200 https://registry.npmjs.org/seedrandom 1077ms (cache miss)
239 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftype-utils 1069ms (cache miss)
240 http fetch GET 200 https://registry.npmjs.org/graphemer 1092ms (cache miss)
241 http fetch GET 200 https://registry.npmjs.org/@nodelib%2ffs.walk 1205ms (cache miss)
242 http fetch GET 200 https://registry.npmjs.org/@eslint%2fjs 1225ms (cache miss)
243 http fetch GET 200 https://registry.npmjs.org/ajv 1268ms (cache miss)
244 http fetch GET 200 https://registry.npmjs.org/chalk 1274ms (cache miss)
245 http fetch GET 200 https://registry.npmjs.org/cross-spawn 1276ms (cache miss)
246 http fetch GET 200 https://registry.npmjs.org/@eslint-community%2fregexpp 1291ms (cache miss)
247 http fetch GET 200 https://registry.npmjs.org/debug 1298ms (cache miss)
248 http fetch GET 200 https://registry.npmjs.org/doctrine 1307ms (cache miss)
249 http fetch GET 200 https://registry.npmjs.org/eslint-scope 1318ms (cache miss)
250 http fetch GET 200 https://registry.npmjs.org/escape-string-regexp 1321ms (cache miss)
251 http fetch GET 200 https://registry.npmjs.org/eslint-visitor-keys 1340ms (cache miss)
252 http fetch GET 200 https://registry.npmjs.org/@humanwhocodes%2fmodule-importer 1353ms (cache miss)
253 http fetch GET 200 https://registry.npmjs.org/esutils 1349ms (cache miss)
254 http fetch GET 200 https://registry.npmjs.org/file-entry-cache 1386ms (cache miss)
255 http fetch GET 200 https://registry.npmjs.org/esquery 1389ms (cache miss)
256 http fetch GET 200 https://registry.npmjs.org/find-up 1402ms (cache miss)
257 http fetch GET 200 https://registry.npmjs.org/espree 1412ms (cache miss)
258 http fetch GET 200 https://registry.npmjs.org/glob-parent 1419ms (cache miss)
259 http fetch GET 200 https://registry.npmjs.org/imurmurhash 1436ms (cache miss)
260 http fetch GET 200 https://registry.npmjs.org/fast-deep-equal 1449ms (cache miss)
261 http fetch GET 200 https://registry.npmjs.org/globals 1461ms (cache miss)
262 http fetch GET 200 https://registry.npmjs.org/is-path-inside 1475ms (cache miss)
263 http fetch GET 200 https://registry.npmjs.org/is-glob 1490ms (cache miss)
264 http fetch GET 200 https://registry.npmjs.org/levn 1493ms (cache miss)
265 http fetch GET 200 https://registry.npmjs.org/json-stable-stringify-without-jsonify 1505ms (cache miss)
266 http fetch GET 200 https://registry.npmjs.org/minimatch 1534ms (cache miss)
267 http fetch GET 200 https://registry.npmjs.org/optionator 1538ms (cache miss)
268 http fetch GET 200 https://registry.npmjs.org/strip-ansi 1547ms (cache miss)
269 http fetch GET 200 https://registry.npmjs.org/cross-spawn 1573ms (cache miss)
270 http fetch GET 200 https://registry.npmjs.org/natural-compare 1582ms (cache miss)
271 http fetch GET 200 https://registry.npmjs.org/@cypress%2frequest 1769ms (cache miss)
272 http fetch GET 200 https://registry.npmjs.org/@types%2fwebgl-ext 1853ms (cache miss)
273 http fetch GET 200 https://registry.npmjs.org/@types%2fvinyl 1856ms (cache miss)
274 http fetch GET 200 https://registry.npmjs.org/@types%2fsizzle 1846ms (cache miss)
275 http fetch GET 200 https://registry.npmjs.org/@types%2fseedrandom 1917ms (cache miss)
276 http fetch GET 200 https://registry.npmjs.org/@types%2fsinonjs__fake-timers 1889ms (cache miss)
277 http fetch GET 200 https://registry.npmjs.org/blob-util 1916ms (cache miss)
278 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 2004ms (cache miss)
279 http fetch GET 200 https://registry.npmjs.org/cachedir 2014ms (cache miss)
280 http fetch GET 200 https://registry.npmjs.org/@cypress%2fxvfb 2041ms (cache miss)
281 http fetch GET 200 https://registry.npmjs.org/chalk 2061ms (cache miss)
282 http fetch GET 200 https://registry.npmjs.org/@types%2foffscreencanvas 2148ms (cache miss)
283 http fetch GET 200 https://registry.npmjs.org/cli-cursor 2083ms (cache miss)
284 http fetch GET 200 https://registry.npmjs.org/check-more-types 2111ms (cache miss)
285 http fetch GET 200 https://registry.npmjs.org/buffer 2117ms (cache miss)
286 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftypes 2174ms (cache miss)
287 http fetch GET 200 https://registry.npmjs.org/@webgpu%2ftypes 2205ms (cache miss)
288 http fetch GET 200 https://registry.npmjs.org/arch 2159ms (cache miss)
289 http fetch GET 200 https://registry.npmjs.org/common-tags 2154ms (cache miss)
290 http fetch GET 200 https://registry.npmjs.org/figures 2194ms (cache miss)
291 http fetch GET 200 https://registry.npmjs.org/cli-table3 2202ms (cache miss)
292 http fetch GET 200 https://registry.npmjs.org/bluebird 2208ms (cache miss)
293 http fetch GET 200 https://registry.npmjs.org/extract-zip 2206ms (cache miss)
294 http fetch GET 200 https://registry.npmjs.org/eventemitter2 2209ms (cache miss)
295 http fetch GET 200 https://registry.npmjs.org/is-ci 2240ms (cache miss)
296 http fetch GET 200 https://registry.npmjs.org/getos 2266ms (cache miss)
297 http fetch GET 200 https://registry.npmjs.org/text-table 2307ms (cache miss)
298 http fetch GET 200 https://registry.npmjs.org/fs-extra 2283ms (cache miss)
299 http fetch GET 200 https://registry.npmjs.org/is-installed-globally 2291ms (cache miss)
300 http fetch GET 200 https://registry.npmjs.org/dayjs 2298ms (cache miss)
301 http fetch GET 200 https://registry.npmjs.org/enquirer 2300ms (cache miss)
302 http fetch GET 200 https://registry.npmjs.org/lazy-ass 2304ms (cache miss)
303 http fetch GET 200 https://registry.npmjs.org/lodash.merge 2357ms (cache miss)
304 http fetch GET 200 https://registry.npmjs.org/lodash 2324ms (cache miss)
305 http fetch GET 200 https://registry.npmjs.org/proxy-from-env 2339ms (cache miss)
306 http fetch GET 200 https://registry.npmjs.org/pretty-bytes 2340ms (cache miss)
307 http fetch GET 200 https://registry.npmjs.org/minimist 2345ms (cache miss)
308 http fetch GET 200 https://registry.npmjs.org/untildify 2393ms (cache miss)
309 http fetch GET 200 https://registry.npmjs.org/supports-color 2393ms (cache miss)
310 http fetch GET 200 https://registry.npmjs.org/semver 2401ms (cache miss)
311 http fetch GET 200 https://registry.npmjs.org/yauzl 2402ms (cache miss)
312 http fetch GET 200 https://registry.npmjs.org/executable 2416ms (cache miss)
313 http fetch GET 200 https://registry.npmjs.org/tmp 2411ms (cache miss)
314 http fetch GET 200 https://registry.npmjs.org/request-progress 2448ms (cache miss)
315 http fetch GET 200 https://registry.npmjs.org/cross-spawn 2446ms (cache miss)
316 http fetch GET 200 https://registry.npmjs.org/human-signals 2454ms (cache miss)
317 http fetch GET 200 https://registry.npmjs.org/is-stream 2458ms (cache miss)
318 http fetch GET 200 https://registry.npmjs.org/get-stream 2465ms (cache miss)
319 http fetch GET 200 https://registry.npmjs.org/signal-exit 2486ms (cache miss)
320 http fetch GET 200 https://registry.npmjs.org/onetime 2489ms (cache miss)
321 http fetch GET 200 https://registry.npmjs.org/npm-run-path 2489ms (cache miss)
322 http fetch GET 200 https://registry.npmjs.org/strip-final-newline 2488ms (cache miss)
323 http fetch GET 200 https://registry.npmjs.org/gulp-cli 2506ms (cache miss)
324 http fetch GET 200 https://registry.npmjs.org/glob-watcher 2511ms (cache miss)
325 http fetch GET 200 https://registry.npmjs.org/undertaker 2545ms (cache miss)
326 http fetch GET 200 https://registry.npmjs.org/cssnano 2549ms (cache miss)
327 http fetch GET 200 https://registry.npmjs.org/buffer-from 2560ms (cache miss)
328 http fetch GET 200 https://registry.npmjs.org/object-assign 2563ms (cache miss)
329 http fetch GET 200 https://registry.npmjs.org/vinyl-fs 2570ms (cache miss)
330 http fetch GET 200 https://registry.npmjs.org/plugin-error 2569ms (cache miss)
331 http fetch GET 200 https://registry.npmjs.org/@eslint%2feslintrc 2660ms (cache miss)
332 http fetch GET 200 https://registry.npmjs.org/vinyl-sourcemaps-apply 2582ms (cache miss)
333 http fetch GET 200 https://registry.npmjs.org/@types%2fvinyl 2594ms (cache miss)
334 http fetch GET 200 https://registry.npmjs.org/argparse 2639ms (cache miss)
335 http fetch GET 200 https://registry.npmjs.org/terser 2652ms (cache miss)
336 http fetch GET 200 https://registry.npmjs.org/through2 2659ms (cache miss)
337 http fetch GET 200 https://registry.npmjs.org/arg 2657ms (cache miss)
338 http fetch GET 200 https://registry.npmjs.org/lazy-ass 2700ms (cache miss)
339 http fetch GET 200 https://registry.npmjs.org/commander 2797ms (cache miss)
340 http fetch GET 200 https://registry.npmjs.org/debug 2756ms (cache miss)
341 http fetch GET 200 https://registry.npmjs.org/bluebird 2764ms (cache miss)
342 http fetch GET 200 https://registry.npmjs.org/yargs-parser 2774ms (cache miss)
343 http fetch GET 200 https://registry.npmjs.org/check-more-types 2778ms (cache miss)
344 http fetch GET 200 https://registry.npmjs.org/merge-stream 2819ms (cache miss)
345 http fetch GET 200 https://registry.npmjs.org/@humanwhocodes%2fconfig-array 2895ms (cache miss)
346 http fetch GET 200 https://registry.npmjs.org/wait-on 2812ms (cache miss)
347 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2ftypescript-estree 3034ms (cache miss)
348 http fetch GET 200 https://registry.npmjs.org/log-symbols 3070ms (cache miss)
349 http fetch GET 200 https://registry.npmjs.org/ospath 3077ms (cache miss)
350 http fetch GET 200 https://registry.npmjs.org/listr2 3138ms (cache miss)
351 http fetch GET 200 https://registry.npmjs.org/replacestream 3402ms (cache miss)
352 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fscope-manager 3600ms (cache miss)
353 http fetch GET 200 https://registry.npmjs.org/ps-tree 3521ms (cache miss)
354 http fetch GET 200 https://registry.npmjs.org/istextorbinary 3571ms (cache miss)
355 timing idealTree:#root Completed in 9936ms
356 silly fetch manifest encoding@^0.1.0
357 http fetch GET 200 https://registry.npmjs.org/encoding 55ms (cache miss)
358 silly placeDep ROOT @types/long@4.0.2 OK for: @tensorflow/tfjs-core@4.4.0 want: ^4.0.1
359 silly placeDep ROOT @types/offscreencanvas@2019.7.0 OK for: @tensorflow/tfjs-core@4.4.0 want: ~2019.7.0
360 silly placeDep ROOT @types/seedrandom@2.4.30 OK for: @tensorflow/tfjs-core@4.4.0 want: ^2.4.28
361 silly placeDep ROOT @types/webgl-ext@0.0.30 OK for: @tensorflow/tfjs-core@4.4.0 want: 0.0.30
362 silly placeDep ROOT @webgpu/types@0.1.30 OK for: @tensorflow/tfjs-core@4.4.0 want: 0.1.30
363 silly placeDep ROOT long@4.0.0 OK for: @tensorflow/tfjs-core@4.4.0 want: 4.0.0
364 silly placeDep ROOT node-fetch@2.6.12 OK for: @tensorflow/tfjs-core@4.4.0 want: ~2.6.1
365 silly fetch manifest whatwg-url@^5.0.0
366 silly placeDep ROOT seedrandom@3.0.5 OK for: @tensorflow/tfjs-core@4.4.0 want: ^3.0.5
367 http fetch GET 200 https://registry.npmjs.org/whatwg-url 120ms (cache miss)
368 timing idealTree:node_modules/@tensorflow/tfjs-core Completed in 186ms
369 silly fetch manifest @aws-sdk/client-s3@3.367.0
370 http fetch GET 200 https://registry.npmjs.org/@aws-sdk%2fclient-s3 372ms (cache miss)
371 silly fetch manifest @aws-sdk/lib-storage@3.367.0
372 http fetch GET 200 https://registry.npmjs.org/@aws-sdk%2flib-storage 1748ms (cache miss)
373 silly fetch manifest @aws-sdk/node-http-handler@3.360.0
374 http fetch GET 200 https://registry.npmjs.org/@aws-sdk%2fnode-http-handler 1741ms (cache miss)
375 silly fetch manifest @bull-board/api@5.6.1
376 http fetch GET 200 https://registry.npmjs.org/@bull-board%2fapi 1720ms (cache miss)
377 silly fetch manifest @bull-board/ui@5.6.1
378 http fetch GET 200 https://registry.npmjs.org/@bull-board%2fui 1702ms (cache miss)
379 silly fetch manifest @bull-board/fastify@5.6.1
380 http fetch GET 200 https://registry.npmjs.org/@bull-board%2ffastify 1770ms (cache miss)
381 silly fetch manifest @discordapp/twemoji@14.1.2
382 http fetch GET 200 https://registry.npmjs.org/@discordapp%2ftwemoji 1702ms (cache miss)
383 silly fetch manifest @fastify/accepts@4.2.0
384 http fetch GET 200 https://registry.npmjs.org/@fastify%2faccepts 1686ms (cache miss)
385 silly fetch manifest @fastify/cookie@8.3.0
386 http fetch GET 200 https://registry.npmjs.org/@fastify%2fcookie 184ms (cache miss)
387 silly fetch manifest @fastify/cors@8.3.0
388 http fetch GET 200 https://registry.npmjs.org/@fastify%2fcors 149ms (cache miss)
389 silly fetch manifest @fastify/http-proxy@9.2.1
390 http fetch GET 200 https://registry.npmjs.org/@fastify%2fhttp-proxy 1680ms (cache miss)
391 silly fetch manifest @fastify/multipart@7.7.1
392 http fetch GET 200 https://registry.npmjs.org/@fastify%2fmultipart 1693ms (cache miss)
393 silly fetch manifest @fastify/static@6.10.2
394 http fetch GET 200 https://registry.npmjs.org/@fastify%2fstatic 138ms (cache miss)
395 silly fetch manifest @fastify/view@8.0.0
396 http fetch GET 200 https://registry.npmjs.org/@fastify%2fview 1761ms (cache miss)
397 silly fetch manifest @nestjs/common@10.1.0
398 http fetch GET 200 https://registry.npmjs.org/@nestjs%2fcommon 145ms (cache miss)
399 silly fetch manifest class-transformer@*
400 http fetch GET 200 https://registry.npmjs.org/class-transformer 45ms (cache miss)
401 silly fetch manifest class-validator@*
402 http fetch GET 200 https://registry.npmjs.org/class-validator 59ms (cache miss)
403 silly fetch manifest reflect-metadata@0.1.13
404 http fetch GET 200 https://registry.npmjs.org/reflect-metadata 48ms (cache miss)
405 silly fetch manifest rxjs@7.8.1
406 http fetch GET 200 https://registry.npmjs.org/rxjs 74ms (cache miss)
407 silly fetch manifest @nestjs/core@10.1.0
408 http fetch GET 200 https://registry.npmjs.org/@nestjs%2fcore 301ms (cache miss)
409 silly fetch manifest @nestjs/microservices@^10.0.0
410 http fetch GET 200 https://registry.npmjs.org/@nestjs%2fmicroservices 1738ms (cache miss)
411 silly fetch manifest @grpc/grpc-js@*
412 http fetch GET 200 https://registry.npmjs.org/@grpc%2fgrpc-js 182ms (cache miss)
413 silly fetch manifest @nestjs/websockets@^10.0.0
414 http fetch GET 200 https://registry.npmjs.org/@nestjs%2fwebsockets 1475ms (cache miss)
415 silly fetch manifest @nestjs/platform-socket.io@^10.0.0
416 http fetch GET 200 https://registry.npmjs.org/@nestjs%2fplatform-socket.io 137ms (cache miss)
417 silly fetch manifest amqp-connection-manager@*
418 http fetch GET 200 https://registry.npmjs.org/amqp-connection-manager 810ms (cache miss)
419 silly fetch manifest amqplib@*
420 http fetch GET 200 https://registry.npmjs.org/amqplib 841ms (cache miss)
421 silly fetch manifest cache-manager@*
422 http fetch GET 200 https://registry.npmjs.org/cache-manager 58ms (cache miss)
423 silly fetch manifest ioredis@5.3.2
424 http fetch GET 200 https://registry.npmjs.org/ioredis 108ms (cache miss)
425 silly fetch manifest kafkajs@*
426 http fetch GET 200 https://registry.npmjs.org/kafkajs 862ms (cache miss)
427 silly fetch manifest mqtt@*
428 http fetch GET 200 https://registry.npmjs.org/mqtt 58ms (cache miss)
429 silly fetch manifest nats@*
430 http fetch GET 200 https://registry.npmjs.org/nats 806ms (cache miss)
431 silly fetch manifest @nestjs/platform-express@^10.0.0
432 http fetch GET 200 https://registry.npmjs.org/@nestjs%2fplatform-express 117ms (cache miss)
433 silly fetch manifest @nestjs/testing@10.1.0
434 http fetch GET 200 https://registry.npmjs.org/@nestjs%2ftesting 127ms (cache miss)
435 silly fetch manifest @peertube/http-signature@1.7.0
436 http fetch GET 200 https://registry.npmjs.org/@peertube%2fhttp-signature 1692ms (cache miss)
437 silly fetch manifest @sinonjs/fake-timers@10.3.0
438 http fetch GET 200 https://registry.npmjs.org/@sinonjs%2ffake-timers 743ms (cache miss)
439 silly fetch manifest @swc/cli@0.1.62
440 http fetch GET 200 https://registry.npmjs.org/@swc%2fcli 165ms (cache miss)
441 silly fetch manifest @swc/core@1.3.70
442 http fetch GET 200 https://registry.npmjs.org/@swc%2fcore 269ms (cache miss)
443 silly fetch manifest @swc/helpers@^0.5.0
444 http fetch GET 200 https://registry.npmjs.org/@swc%2fhelpers 171ms (cache miss)
445 silly fetch manifest chokidar@3.5.3
446 silly fetch manifest accepts@1.3.8
447 http fetch GET 200 https://registry.npmjs.org/accepts 49ms (cache miss)
448 silly fetch manifest ajv@8.12.0
449 silly fetch manifest archiver@5.3.1
450 http fetch GET 200 https://registry.npmjs.org/archiver 80ms (cache miss)
451 silly fetch manifest async-mutex@^0.4.0
452 http fetch GET 200 https://registry.npmjs.org/async-mutex 58ms (cache miss)
453 silly fetch manifest bcryptjs@2.4.3
454 http fetch GET 200 https://registry.npmjs.org/bcryptjs 41ms (cache miss)
455 silly fetch manifest blurhash@2.0.5
456 http fetch GET 200 https://registry.npmjs.org/blurhash 60ms (cache miss)
457 silly fetch manifest bullmq@4.4.0
458 http fetch GET 200 https://registry.npmjs.org/bullmq 979ms (cache miss)
459 silly fetch manifest cacheable-lookup@7.0.0
460 http fetch GET 200 https://registry.npmjs.org/cacheable-lookup 48ms (cache miss)
461 silly fetch manifest cbor@9.0.0
462 http fetch GET 200 https://registry.npmjs.org/cbor 800ms (cache miss)
463 silly fetch manifest chalk@5.3.0
464 silly fetch manifest chalk-template@1.1.0
465 http fetch GET 200 https://registry.npmjs.org/chalk-template 843ms (cache miss)
466 silly fetch manifest cli-highlight@2.1.11
467 http fetch GET 200 https://registry.npmjs.org/cli-highlight 56ms (cache miss)
468 silly fetch manifest color-convert@2.0.1
469 http fetch GET 200 https://registry.npmjs.org/color-convert 117ms (cache miss)
470 silly fetch manifest content-disposition@0.5.4
471 http fetch GET 200 https://registry.npmjs.org/content-disposition 52ms (cache miss)
472 silly fetch manifest date-fns@2.30.0
473 http fetch GET 200 https://registry.npmjs.org/date-fns 86ms (cache miss)
474 silly fetch manifest deep-email-validator@0.1.21
475 http fetch GET 200 https://registry.npmjs.org/deep-email-validator 797ms (cache miss)
476 silly fetch manifest fastify@4.20.0
477 http fetch GET 200 https://registry.npmjs.org/fastify 122ms (cache miss)
478 silly fetch manifest feed@4.2.2
479 http fetch GET 200 https://registry.npmjs.org/feed 826ms (cache miss)
480 silly fetch manifest file-type@18.5.0
481 http fetch GET 200 https://registry.npmjs.org/file-type 84ms (cache miss)
482 silly fetch manifest fluent-ffmpeg@2.1.2
483 http fetch GET 200 https://registry.npmjs.org/fluent-ffmpeg 838ms (cache miss)
484 silly fetch manifest form-data@4.0.0
485 http fetch GET 200 https://registry.npmjs.org/form-data 46ms (cache miss)
486 silly fetch manifest got@13.0.0
487 http fetch GET 200 https://registry.npmjs.org/got 69ms (cache miss)
488 silly fetch manifest happy-dom@10.0.3
489 http fetch GET 200 https://registry.npmjs.org/happy-dom 213ms (cache miss)
490 silly fetch manifest hpagent@1.2.0
491 http fetch GET 200 https://registry.npmjs.org/hpagent 88ms (cache miss)
492 silly fetch manifest ip-cidr@3.1.0
493 http fetch GET 200 https://registry.npmjs.org/ip-cidr 873ms (cache miss)
494 silly fetch manifest ipaddr.js@2.1.0
495 http fetch GET 200 https://registry.npmjs.org/ipaddr.js 41ms (cache miss)
496 silly fetch manifest is-svg@5.0.0
497 http fetch GET 200 https://registry.npmjs.org/is-svg 49ms (cache miss)
498 silly fetch manifest jsdom@22.1.0
499 http fetch GET 200 https://registry.npmjs.org/jsdom 94ms (cache miss)
500 silly fetch manifest canvas@^2.5.0
501 http fetch GET 200 https://registry.npmjs.org/canvas 56ms (cache miss)
502 silly fetch manifest json5@2.2.3
503 http fetch GET 200 https://registry.npmjs.org/json5 50ms (cache miss)
504 silly fetch manifest jsonld@8.2.0
505 http fetch GET 200 https://registry.npmjs.org/jsonld 890ms (cache miss)
506 silly fetch manifest jsrsasign@10.8.6
507 http fetch GET 200 https://registry.npmjs.org/jsrsasign 901ms (cache miss)
508 silly fetch manifest meilisearch@0.33.0
509 http fetch GET 200 https://registry.npmjs.org/meilisearch 826ms (cache miss)
510 silly fetch manifest mfm-js@0.23.3
511 http fetch GET 200 https://registry.npmjs.org/mfm-js 830ms (cache miss)
512 silly fetch manifest mime-types@2.1.35
513 http fetch GET 200 https://registry.npmjs.org/mime-types 40ms (cache miss)
514 timing idealTree Completed in 50506ms
515 timing command:update Completed in 50524ms
516 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
516 verbose stack     at unsupportedURLType (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:327:15)
516 verbose stack     at fromURL (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:387:13)
516 verbose stack     at Function.resolve (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
516 verbose stack     at #nodeFromEdge (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1048:22)
516 verbose stack     at #buildDepStep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:35)
516 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
516 verbose stack     at async Promise.all (index 1)
516 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
516 verbose stack     at async Update.exec (/usr/lib/node_modules/npm/lib/commands/update.js:64:5)
516 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:89:5)
517 verbose cwd /home/misskey/misskey
518 verbose Linux 5.15.30-2-pve
519 verbose node v20.5.0
520 verbose npm  v9.6.6
521 error code EUNSUPPORTEDPROTOCOL
522 error Unsupported URL Type "workspace:": workspace:*
523 verbose exit 1
524 timing npm Completed in 50783ms
525 verbose unfinished npm timer reify 1690121712216
526 verbose unfinished npm timer reify:loadTrees 1690121712228
527 verbose unfinished npm timer idealTree:buildDeps 1690121712315
528 verbose unfinished npm timer idealTree:packages/backend 1690121722437
529 verbose code 1
530 error A complete log of this run can be found in: /home/misskey/.npm/_logs/2023-07-23T14_15_11_949Z-debug-0.log

````

**Comment by iambeingtracked** [comment]
Okay, so it was basically trying to pull slacc 0.0.9 because package.json in packages/backend had 0.0.9 and not 0.0.10, I changed it, made it build with no lockfile and everything worked, for proper work Misskey has to update it, I won't make a pull request as I don't know much node and I don't want to deal with hash sums now. Closing the issue, thanks to everyone who helped

**Comment by Yonle** [comment]
well, it seems happening again with my misskey on alpine incus container.

```
misskey:~/misskey$ pnpm add -w slacc-linux-x64-musl
 ERR_PNPM_UNSUPPORTED_PLATFORM  Unsupported platform for slacc-linux-x64-musl@0.0.10: wanted {"cpu":["x64"],"os":["linux"],"libc":["glibc"]} (current: {"os":"linux","cpu":"x64","libc":"musl"})
```

it should expecting musl libc, not glibc
